//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurtmolaServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data
    {
        public int Id { get; set; }
        public string type { get; set; }
        public string addedDate { get; set; }
        public string data { get; set; }
        public int FolderId { get; set; }
    
        public virtual Folder Folder { get; set; }
    }
}
